### ISSUE TITLE
Accessibility icons are sub-quality

### ISSUE THREAD

**Issue by jcayzac** [zurb/foundation-icon-fonts#5]
The accessibility icons are awful. The wheelchair looks like a crab (is that a para-olympic racer? i understand [1] below much better) and the whole subset is barely readable at all at small sizes. Why is the stroke width so thin compared with the rest of the font?

[1] standard wheelchair icon
![](http://4vector.com/i/free-vector-disabled-wheel-chair-access-sign-clip-art_110475_Disabled_Wheel_Chair_Access_Sign_clip_art_small.png)

**Comment by rafibomb** [comment]
This is the guidlines - http://www.accessibleicon.org/icon.html - we'll take a look
